// <auto-generated />
using System;
using Emigrant.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emigrant.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Emigrant.App.Dominio.Entidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoEntidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nit")
                        .HasColumnType("int");

                    b.Property<string>("razon_Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sector")
                        .HasColumnType("int");

                    b.Property<string>("telefonoEntidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipoServicio")
                        .HasColumnType("int");

                    b.Property<string>("web")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.Migrante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ciudad")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha_nacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sit_laboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_documento")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Migrantes");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.Necesidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Migrante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Migranteid")
                        .HasColumnType("int");

                    b.Property<string>("detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prioridad")
                        .HasColumnType("int");

                    b.Property<int>("tipoServicio")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Migranteid");

                    b.ToTable("Necesidades");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.Novedad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ciudad")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("fechaNovedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_entidad")
                        .HasColumnType("int");

                    b.Property<string>("novedad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroDias")
                        .HasColumnType("int");

                    b.Property<int>("tipoNovedad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.grupoMigrante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Migranteid")
                        .HasColumnType("int");

                    b.Property<int>("id_migrante")
                        .HasColumnType("int");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("parentesco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Migranteid");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.servicios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("fechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaIni")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreServicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numCupos")
                        .HasColumnType("int");

                    b.Property<int>("prioridad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.Necesidad", b =>
                {
                    b.HasOne("Emigrant.App.Dominio.Migrante", null)
                        .WithMany("necesidades")
                        .HasForeignKey("Migranteid");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.grupoMigrante", b =>
                {
                    b.HasOne("Emigrant.App.Dominio.Migrante", null)
                        .WithMany("GrupoMigrantes")
                        .HasForeignKey("Migranteid");
                });

            modelBuilder.Entity("Emigrant.App.Dominio.Migrante", b =>
                {
                    b.Navigation("GrupoMigrantes");

                    b.Navigation("necesidades");
                });
#pragma warning restore 612, 618
        }
    }
}
